name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[BUG]: "
labels: [ "bug" ]
assignees: [ ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead?
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Drag and drop screenshots here...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How critical is this bug?
      options:
        - Low - Minor issue
        - Medium - Affects functionality
        - High - Blocks major functionality
        - Critical - App crashes or unusable
    validations:
      required: true

  - type: textarea
    id: device
    attributes:
      label: Device Information
      description: Information about your device
      placeholder: |
        - Device: [e.g. Samsung Galaxy S21]
        - OS Version: [e.g. Android 12]
        - App Version: [e.g. 0.6.2]
      render: markdown

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information...
