name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE]: "
labels: [ "feature" ]
assignees: [ ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! ✨

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered.
      placeholder: I've also considered...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Important for productivity
        - Critical - Essential functionality
    validations:
      required: true

  - type: checkboxes
    id: scope
    attributes:
      label: Feature Scope
      description: What areas would this feature affect?
      options:
        - label: User Interface (UI)
        - label: User Experience (UX)
        - label: Backend/Data
        - label: Performance
        - label: Security
        - label: Integration with external services

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Wireframes
      description: If you have any mockups, wireframes, or visual ideas, please share them.
      placeholder: Drag and drop images here...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request.
      placeholder: Any additional information...
