name: 📦 Release
description: Prepare a new version release
title: "[EXSHAPP-XXXX]: Release - vX.Y.Z"
labels: [ "release" ]
assignees: [ "pedrazamiguez" ]
body:
  - type: markdown
    attributes:
      value: |
        ### Release Preparation
        This issue triggers the automated release flow. A branch `release/EXSHAPP-XXXX` will be created and a PR to `main` will be opened automatically.

  - type: checkboxes
    id: release_type
    attributes:
      label: Release Type
      description: Is this a breaking change?
      options:
        - label: Major Release (Breaking Changes)
          required: false

  - type: textarea
    id: notes
    attributes:
      label: Release Notes / Context
      description: Any specific notes for this release (optional).
      placeholder: Summary of changes...
